# Generated by Django 2.2 on 2020-04-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phone',
            name='sale_price',
            field=models.CharField(default='10', max_length=100),
        ),
    ]
