# Generated by Django 2.2 on 2020-04-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20200417_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='final_price',
            field=models.CharField(default='', max_length=100),
        ),
    ]
