# Generated by Django 2.2 on 2020-04-20 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='final_price',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
