# Generated by Django 2.2 on 2020-04-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20200420_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='final_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
